### ISSUE TITLE
Macaron style feed-forward neural network in Conformer

### ISSUE THREAD

**Issue by joyolee** [speechbrain/speechbrain#621] opened 2021-04-02 11:58 UTC
Hi,
in the speechbrain's implementation of macaron style FFN, the two half FFNs are actually the same one if I understand correctly? Namely, these two half FFNs share their parameters. Code： https://github.com/speechbrain/speechbrain/blob/92ab7c0e13935891256ffb6abfe8a8bd3075c292/speechbrain/lobes/models/transformer/conformer.py#L160-L173 

In the paper Conformer (https://arxiv.org/abs/2005.08100), there's no clear explanation. In the implementation of original macaron implementation (paper: https://arxiv.org/pdf/1906.02762.pdf) Code: 
https://github.com/zhuohan123/macaron-net/blob/3a84e7a3323bd1a3a9a303194ba336d670a1fb2c/translation/fairseq/models/transformer.py#L554-L556
and ESPnet, these two half FFNs are different.  

I would ask if you do it on purpose or if it's a bug?

Best regards

**Comment by mravanelli** [comment] 2021-04-03 01:16
@JianyuanZhong

**Comment by TParcollet** [comment] 2021-04-18 08:40
Hey @joyolee have you been able to correct this on your code and try it ?

**Comment by TParcollet** [comment] 2021-04-18 08:47
Because it looks indeed incorrect from our side (w.r.t the implementation you mentioned).

**Comment by TParcollet** [comment] 2021-04-18 08:54
Right @joyolee, I am not an expert on this, but our implementation match the description of: https://arxiv.org/pdf/2005.08100.pdf 

Look at Figure 1 and 4. You will see on Figure 1 that you have twice 1/2 Feed Forward Module; Then on Figure 4 you'll find that a Feed Forward Module is comprised with different blocks (and mostly with 2 dense layers). Now, on our code we apply twice the ffn_module that is a sequential containing exactly what is describe in Figure 4. 

HOWEVER, if you think we are wrong somewhere, please let us know. We are not able to reproduce the results of the paper for now ....

**Comment by joyolee** [comment] 2021-04-18 09:19
Hey @TParcollet, thanks for your reply. I haven't tried it with Speechbrain, because the Librispeech recipe is relatively large for my experiment environment.

I have read the paper 'Conformer'. In my opinion, the paper doesn't describe the Conformer's structure in detail. I was also confused with the two FFN blocks in the figure. About the correctness, I might need to write an email to the author to ask. In another paper: https://arxiv.org/abs/2102.06657
which uses the conformer encoders for audio-visual tasks. It points out clearly that the second half-step FFN is ANOTHER FFN.

And for the implementation in ESPnet:
https://github.com/espnet/espnet/blob/a9215256fd8d2978ad24886dd4041b487dc018fe/espnet2/asr/encoder/conformer_encoder.py#L243-L253

If I understand correctly, I think they also use 2 different FFNs in each encoder block. By using ESPnet toolkit, I did experiments with conformer structure on WSJ  (81 hours). It does have improvement compared with the transformer.

I would ask, how do the results look like in LibriSpeech when you use two similar FFN, could you post it?

Best regards,
Zhengyang

**Comment by TParcollet** [comment] 2021-04-18 09:54
They do not look that good. But what you are pointing out might be the issue.

**Comment by TParcollet** [comment] 2021-04-18 09:54
We'll try to get someone working on this ASAP, but we would love to get some help also :-P

**Comment by joyolee** [comment] 2021-04-18 11:35
Cool, it would be good if I can help a little.

**Comment by popcornell** [comment] 2021-04-18 23:37
There is actually a wrong skip connection also. We need to fix that ASAP. 
I can fix it but I can't run experiments on LibriSpeech as it will clog all my resources for too much time.

**Comment by mravanelli** [comment] 2021-04-20 23:46
@popcornell could you please ask for a PR to fix that?

**Comment by popcornell** [comment] 2021-04-26 11:16
I am fixing the Conformer architecture here. I added relative positional encodings too as Conformer uses those see PR: https://github.com/speechbrain/speechbrain/pull/535 . 
@joyolee feel free to take a look if you want

**Comment by TParcollet** [comment] 2021-06-03 08:58
Being fixed in #535.

**Closed by TParcollet** 2021-06-03 08:58 UTC
