### ISSUE TITLE
recipes/Common voice issue

### ISSUE THREAD

**Issue by monaabdelazim** [speechbrain/speechbrain#1024] opened 2021-10-01 23:16 UTC
I have been trying to apply the common voice recipe to a new language and i could manage to construct the data files but when i have reached the fit step i got this error:
speechbrain.tokenizers.SentencePiece - Tokenizer is already trained.
speechbrain.tokenizers.SentencePiece - ==== Loading Tokenizer ===
speechbrain.tokenizers.SentencePiece - Tokenizer path: results/CRDNN_it/1234/save\500_unigram.model
speechbrain.tokenizers.SentencePiece - Tokenizer vocab_size: 500
speechbrain.tokenizers.SentencePiece - Tokenizer type: unigram
speechbrain.core - 148.2M trainable parameters in ASR
speechbrain.utils.checkpoints - Would load a checkpoint here, but none found yet.
speechbrain.utils.epoch_loop - Going into epoch 1
  0%|                                                                                         | 0/2140 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Mona\anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Mona\anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train.py", line 329, in <module>
    asr_brain.fit(
  File "C:\Users\Mona\anaconda3\lib\site-packages\speechbrain\core.py", line 1031, in fit
    for batch in t:
  File "C:\Users\Mona\anaconda3\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\Users\Mona\anaconda3\lib\site-packages\speechbrain\dataio\dataloader.py", line 206, in __iter__
    iterator = super().__iter__()
  File "C:\Users\Mona\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Users\Mona\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Mona\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Users\Mona\anaconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Mona\anaconda3\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Mona\anaconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Mona\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Mona\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'dataio_prepare.<locals>.audio_pipeline'

**Comment by TParcollet** [comment] 2021-10-04 10:17
@Gastron Do you think this can due to a problem in the definition of the audio pipeline ? @monaabdelazim, could you please post you .py files as well ?

**Comment by Gastron** [comment] 2021-10-04 11:27
Yeah there is some issue with how the data loading pipeline functions get defined. If you can share the Python training script it might be easy to spot what you need to change.

**Comment by monaabdelazim** [comment] 2021-10-04 20:59
Find belpw the train script.
[train.txt](https://github.com/speechbrain/speechbrain/files/7281285/train.txt)
Thanks in advance.

**Comment by Gastron** [comment] 2021-10-05 09:40
Huh, similar code actually works fine. But I think I know what the issue is. You're using the `spawn` (Windows default) method for creating the background data loading processes, instead of `fork` (Unix default). You're working on Windows, so the `fork` method for creating a process is not available. The short explanation is, as far as I understand it, in this case, that `fork` copies everything in memory, `spawn` pickles stuff so that it could be recreated, so things like the dynamic items created in `dataio_prepare` cannot be transferred to the background process by `spawn`. So the dynamic items should be moved into the module level (outside `dataio_prepare`). 

I've sketched a very hacky and ugly solution, but I've not tested it. Taking the audio pipeline definition outside `dataio_prepare` is easy. However, the text pipeline is tricky because it uses the dynamically loaded / created tokenizer. I think the easiest solution in this case is to just hard code the tokenizer arguments and put it into the module level code as well. (See the code, you need to fill in the arguments from your hparams file.)

```python
# Define audio pipeline:
@sb.utils.data_pipeline.takes("wav")
@sb.utils.data_pipeline.provides("sig")
def audio_pipeline(wav):
    info = torchaudio.info(wav)
    sig = sb.dataio.dataio.read_audio(wav)
    if info.num_channels > 1:
        sig = torch.mean(sig, dim=1)
    resampled = torchaudio.transforms.Resample(
        info.sample_rate, hparams["sample_rate"],
    )(sig)
    return resampled

# Load tokenizer in global scope (ugly hack, sorry!)
# TODO: Fill in the values from hparams manually.
tokenizer = SentencePiece(
    model_dir=...,
    vocab_size=...,
    annotation_train=...,
    annotation_read="wrd",
    model_type=...,
    character_coverage=...,
)

# Define text pipeline:
@sb.utils.data_pipeline.takes("wrd")
@sb.utils.data_pipeline.provides(
    "tokens_list", "tokens_bos", "tokens_eos", "tokens"
)
def text_pipeline(wrd):
    tokens_list = tokenizer.sp.encode_as_ids(wrd)
    yield tokens_list
    tokens_bos = torch.LongTensor([hparams["bos_index"]] + (tokens_list))
    yield tokens_bos
    tokens_eos = torch.LongTensor(tokens_list + [hparams["eos_index"]])
    yield tokens_eos
    tokens = torch.LongTensor(tokens_list)
    yield tokens


# Define custom data procedure
def dataio_prepare(hparams, tokenizer):
    """This function prepares the datasets to be used in the brain class.
    It also defines the data processing pipeline through user-defined functions."""

    # 1. Define datasets
    data_folder = hparams["data_folder"]

    train_data = sb.dataio.dataset.DynamicItemDataset.from_csv(
        csv_path=hparams["train_csv"], replacements={"data_root": data_folder},
    )

    if hparams["sorting"] == "ascending":
        # we sort training data to speed up training and get better results.
        train_data = train_data.filtered_sorted(
            sort_key="duration",
            key_max_value={"duration": hparams["avoid_if_longer_than"]},
        )
        # when sorting do not shuffle in dataloader ! otherwise is pointless
        hparams["dataloader_options"]["shuffle"] = False

    elif hparams["sorting"] == "descending":
        train_data = train_data.filtered_sorted(
            sort_key="duration",
            reverse=True,
            key_max_value={"duration": hparams["avoid_if_longer_than"]},
        )
        # when sorting do not shuffle in dataloader ! otherwise is pointless
        hparams["dataloader_options"]["shuffle"] = False

    elif hparams["sorting"] == "random":
        pass

    else:
        raise NotImplementedError(
            "sorting must be random, ascending or descending"
        )

    valid_data = sb.dataio.dataset.DynamicItemDataset.from_csv(
        csv_path=hparams["valid_csv"], replacements={"data_root": data_folder},
    )
    # We also sort the validation data so it is faster to validate
    valid_data = valid_data.filtered_sorted(sort_key="duration")

    test_data = sb.dataio.dataset.DynamicItemDataset.from_csv(
        csv_path=hparams["test_csv"], replacements={"data_root": data_folder},
    )

    # We also sort the validation data so it is faster to validate
    test_data = test_data.filtered_sorted(sort_key="duration")

    datasets = [train_data, valid_data, test_data]



    sb.dataio.dataset.add_dynamic_item(datasets, audio_pipeline)


    sb.dataio.dataset.add_dynamic_item(datasets, text_pipeline)

    # 4. Set output:
    sb.dataio.dataset.set_output_keys(
        datasets, ["id", "sig", "tokens_bos", "tokens_eos", "tokens"],
    )
    return train_data, valid_data, test_data
```

**Comment by TParcollet** [comment] 2021-10-07 15:17
Is the issue solved ?

**Comment by Adel-Moumen** [comment] 2022-09-06 14:20
Hello,

any updates on this issue? is the issue still up?

**Comment by Adel-Moumen** [comment] 2022-09-26 18:14
Hello, 

There has been no activity for a very long time. Therefore, I am closing this issue. 

Feel free to reopen if needed. Thanks! :)

**Closed by Adel-Moumen** 2022-09-26 18:14 UTC
