### ISSUE TITLE
Inference speed on CPU - HF models

### ISSUE THREAD

**Issue by amtam0** [speechbrain/speechbrain#1145] opened 2021-11-19 22:27 UTC
Hi,

I deployed pretrained HF models(speechbrain/asr-wav2vec2-commonvoice-en, speechbrain/lang-id-commonlanguage_ecapa) in Cloud Run(serverless cpu), the process time is slow (3 to 4 seconds).
Is it possible to compress these models in order to improve inference speed on CPU ? Any tips are welcome.

Thanks

**Comment by mravanelli** [comment] 2021-11-19 23:00
Hi,
The asr-wav2vec2-commonvoice-en is a huge model and thus slow.  If you are
looking something faster, you can train the seq2seq CRDNN model with
CommonVoice-english data (
https://github.com/speechbrain/speechbrain/tree/develop/recipes/CommonVoice/ASR/seq2seq).
As an alternative, you can consider the available CRDNN model pretrained on
LibriSpeech (https://huggingface.co/speechbrain/asr-crdnn-rnnlm-librispeech).
Note that usually the price to pay for a more efficient model is
performance. So far, we did not focus too much on small-footprint models,
but we plan to work more on that in the future. The
lang-id-commonlanguage_ecapa, instead, is not a big model and it should be
able to run faster.

**Comment by amtam0** [comment] 2021-11-19 23:41
Thank you for your answer, the HF pre-trained CRDNN model seems ok for my use case.
Sorry I forgot to mention that I am also using this model https://huggingface.co/speechbrain/asr-wav2vec2-commonvoice-fr
I saw a Medium [link](https://medium.com/georgian-impact-blog/compressing-wav2vec-2-0-f41166e82dc2) about compressing wav2vec models. Do you think these methods may improve inference speed ? Are they compatible with speechbrain library?
Thanks

**Comment by mravanelli** [comment] 2021-11-20 02:08
Yes, this and other methods towards small-footprint models are interesting.
We plan to work on this topic in the future and the help of the community
is welcome!

**Comment by aheba** [comment] 2021-11-23 13:12
Hi @amtam0 , If you think that the issue is addressed, please, feel free to close the issue

**Closed** 2021-11-24 10:04 UTC
