### ISSUE TITLE
[Bug]: Can't pickle an EncoderDecoderASR because of functools._lru_cache

### ISSUE THREAD

**Issue by lucilemg** [speechbrain/speechbrain#1965] opened 2023-05-02 14:51 UTC
### Describe the bug

When trying to export a package with a pickled EncoderDecoderASR object, the pickle operation does not work. From this [similar issue](https://stackoverflow.com/questions/54363043/pickling-lru-cached-function-on-object) (non related to Speechbrain) seems to come from the pickle module that has issues when dealing with decorators. Although the issue comes from the pickle module, maybe there's a way around to be able to pickle a model ?

The issue is caused by a decorator in speechbrain/dataio/preprocess.py in the AudioNormalizer class. When initiating an EncoderDecoderASR object (and thus a Pretrained class), an AudioNormalizer is initialized (see [code](https://github.com/speechbrain/speechbrain/blob/0423bda83237070ad219d88b834d480f58cbe53e/speechbrain/pretrained/interfaces.py#L225)). In its `__init__` function (see [code](https://github.com/speechbrain/speechbrain/blob/0423bda83237070ad219d88b834d480f58cbe53e/speechbrain/dataio/preprocess.py#L44)), it creates `self._cached_resample` with `functools.lru_cache` for the Resample class, which causes the error below.

### Expected behaviour

The package should be created with the pickled model inside.

### To Reproduce

```
from torch import package
from speechbrain.pretrained import EncoderDecoderASR

if __name__ == "__main__":
    asr_model = EncoderDecoderASR.from_hparams(
    	source="speechbrain/asr-transformer-switchboard",
    )

    with package.PackageExporter("test_pickle.pt", debug=True) as exp:
        exp.extern("speechbrain.**")
        exp.intern("__main__")
        exp.save_pickle("binary", "test_pickle.pkl", asr_model)
```

### Versions

speechbrain 0.5.14
torch 2.0.0
torchaudio 2.0.1

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/lucile/speech_repo/speech-lab/modelling/use_cases/test_pickle_issue.py", line 15, in <module>
    exp.save_pickle("binary", "test_pickle.pkl", asr_model)
  File "/home/lucile/speech_repo/speech-lab/modelling/.venv/lib/python3.9/site-packages/torch/package/package_exporter.py", line 631, in save_pickle
    pickler.dump(obj)
_pickle.PicklingError: Can't pickle <functools._lru_cache_wrapper object at 0x7f5d9c6dba40>: it's not the same object as speechbrain.processing.speech_augmentation.Resample
```

**Comment by lucilemg** [comment] 2023-05-02 16:21
It works by following [this solution](https://stackoverflow.com/a/55992364) and modifying the speechbrain files in local. I submitted a [PR](https://github.com/speechbrain/speechbrain/pull/1966) on speechbrain repository.

**Comment by Adel-Moumen** [comment] 2023-05-15 12:51
Hey @lucilemg and @courentin,

it seems that this issue has been fixed in #1966. Therefore I'm closing this issue. 

Please re-open if the issue is still up. Thanks! :)

**Closed by Adel-Moumen** 2023-05-15 12:51 UTC
Labels: bug

**Comment by courentin** [comment] 2023-05-15 13:09
Thank you for your message @Adel-Moumen, unfortunately the fix is not available in the latest release of speecbrain

Would it be possible to trigger a 0.5.15 release version of the speechbrain package?

That would avoid us to pin our project to a git revision :)

**Comment by Adel-Moumen** [comment] 2023-05-15 13:59
Yes, I agree. I will talk about this with the other members of the core team. I let you know when I have more informations. Thanks again for your feedbacks!

**Comment by Adel-Moumen** [comment] 2023-05-16 15:35
Hey, I've been in talk with the other maintainers. We agreed and I will try to release a new version this week! @courentin

**Comment by courentin** [comment] 2023-05-16 15:40
This is good news, thank you very much @Adel-Moumen  🙏
