### ISSUE TITLE
Wav2Vec2WordpieceTokenizer' object has no attribute '_create_trie'

### ISSUE THREAD

**Issue by TienMinhHoa** [speechbrain/speechbrain#2554] opened 2024-05-23 09:09 UTC
### Describe the bug

I am facing with this problem
![image](https://github.com/speechbrain/speechbrain/assets/114821401/5f45ee73-26f1-4c52-bf70-e9307d5889fe)
when I tried to load pretrained model:
![image](https://github.com/speechbrain/speechbrain/assets/114821401/dc715b4e-80e2-4c1c-a878-5522045b8e09)

### Expected behaviour

I hope the model can work

**Comment by TParcollet** [comment] 2024-05-31 12:21
Hello, could you give more info? I can't replicate, see picture.
<img width="1781" alt="image" src="https://github.com/speechbrain/speechbrain/assets/11910731/f45eaee0-50b9-47ac-994f-b0c489b9cebe">

**Comment by asumagic** [comment] 2024-06-05 12:49
I cannot reproduce this either, and I suspect the reason for this is because you set the save directory of `speechbrain/asr-wav2vec2-commonvoice-fr` to a directory (`pretrained_models/asr-wav2vec2-vi`) that already contains a different model, which would end up in this kind of file confusion.

I will close this for now, feel free to reopen if this still happens for you on a clean savedir.

**Closed by asumagic** 2024-06-05 12:49 UTC
Labels: bug
