### ISSUE TITLE
Out of range: piece id is out of range

### ISSUE THREAD

**Issue by Jxu-Thu** [speechbrain/speechbrain#1183] opened 2021-12-08 07:44 UTC
Branch：master
I run the SLURP experiments based on HuBERT initialization following https://github.com/speechbrain/speechbrain/tree/develop/recipes/SLURP.

I got the error 

IndexError: Out of range: piece id is out of range. 

The error is the same as the log file provided by official log.txt [checkpoints](https://drive.google.com/drive/folders/1LpcuFldRo_Va1OCGp1bLNdiaC7AQNJOb).

How can I avoid this error?

**Comment by Moumeneb1** [comment] 2021-12-09 19:22
Hi, I'm running the issue to check, a first thing is that the path speechbrain/SLU-direct-SLURP-wav2vec-enc no longer exists on the speechbrain hub, you have to change :

```yaml
tokenizer_file: speechbrain/SLU-direct-SLURP-wav2vec-enc
```
to 
```yaml
tokenizer_file: speechbrain/SLU-direct-SLURP-hubert-enc
```
and 
```yaml
tokenizer: !ref <tokenizer_file>/SLURP_58_unigram.model
```
to 

```yaml
tokenizer: !ref <tokenizer_file>/tokenizer_58_unigram.model
```

**Comment by mravanelli** [comment] 2021-12-09 19:25
Can we fix it?

**Comment by Gastron** [comment] 2021-12-09 20:55
![image](https://user-images.githubusercontent.com/5797214/145474184-29860782-fd9b-432a-94d3-09c5d2fd6e0d.png)

**Comment by aheba** [comment] 2021-12-10 09:18
Hello @Jxu-Thu , thank you for reporting the issue, let me do a fix,

**Comment by Moumeneb1** [comment] 2021-12-10 15:38
Hi @Jxu-Thu  The issue is that the tokenizer only generates 51 tokens and not 58. I personally trained the model on real data only, so I didn't noticed this issue. What I found interesting while debugging and it's the thing that is causing this issue is the use of the synthetic data. The issue is that the predicted ids, when using only real data on the first batches, the neurons52 to 57 don't get activated so I didn't encounter it. However, the synthetic data is more perturbating ( at least at first when the layer is not trained). I'll pull request the fix. 
Thanks for the reporting !

**Comment by aheba** [comment] 2021-12-17 13:43
@Jxu-Thu , thank you for reporting the issue, The PR #1186  is merged :).

Feel Free to share with us any other issues ;)

**Closed by aheba** 2021-12-17 13:43 UTC

**Comment by zhengqing187** [comment] 2023-06-18 12:28
Traceback (most recent call last):
  File "train_with_wav2vec2.py", line 379, in <module>
    valid_loader_kwargs=hparams["dataloader_opts"],
  File "/home/zhaochen/anaconda3/envs/SLU/lib/python3.7/site-packages/speechbrain/core.py", line 1226, in fit
    self._fit_valid(valid_set=valid_set, epoch=epoch, enable=enable)
  File "/home/zhaochen/anaconda3/envs/SLU/lib/python3.7/site-packages/speechbrain/core.py", line 1129, in _fit_valid
    loss = self.evaluate_batch(batch, stage=Stage.VALID)
  File "train_with_wav2vec2.py", line 161, in evaluate_batch
    loss = self.compute_objectives(predictions, batch, stage=stage)
  File "train_with_wav2vec2.py", line 94, in compute_objectives
    for utt_seq in predicted_tokens
  File "train_with_wav2vec2.py", line 94, in <listcomp>
    for utt_seq in predicted_tokens
  File "/home/zhaochen/anaconda3/envs/SLU/lib/python3.7/site-packages/sentencepiece/__init__.py", line 837, in DecodeIds
    return self.Decode(input=input, out_type=out_type, **kwargs)
  File "/home/zhaochen/anaconda3/envs/SLU/lib/python3.7/site-packages/sentencepiece/__init__.py", line 780, in Decode
    return self._DecodeIds(input)
  File "/home/zhaochen/anaconda3/envs/SLU/lib/python3.7/site-packages/sentencepiece/__init__.py", line 337, in _DecodeIds
    return _sentencepiece.SentencePieceProcessor__DecodeIds(self, ids)
IndexError: Out of range: piece id is out of range.
@Jxu-Thu  Can you tell me how you solved this problem?

**Comment by zhengqing187** [comment] 2023-06-18 14:05
hello,

the tokenizer only generates 51 tokens and not 58,Why is it 51 and not 58 and how do I understand this 51? I just need to change 58 to 51 as you suggested (output_neurons: 51 # index(eos/bos) = 0)? Thank you very much.

Best wish to you.
@Moumeneb1
