### ISSUE TITLE
Segmentation fault (core dumped) anytime importing fairseq after speechbrain

### ISSUE THREAD

**Issue by mhn226** [speechbrain/speechbrain#1534] opened 2022-08-09 07:48 UTC
Hi,

I have this weird issue anytime trying to import fairseq after speechbrain:  Segmentation fault (core dumped)

The other way around (importing fairseq before speechbrain) seems OK.

Does anyone have an idea of what happened?

**Comment by TParcollet** [comment] 2022-08-10 09:25
<img width="507" alt="Capture d’écran 2022-08-10 à 11 24 54" src="https://user-images.githubusercontent.com/11910731/183866058-f212c5d8-74f2-42b1-b47e-090bde460027.png">
Hi, unfortunately, unable to reproduce the error :-(

**Comment by Adel-Moumen** [comment] 2022-09-06 13:42
Hello, I am too also unable to reproduce the error. 

Could you please tell me if the segmentation fault is still happening?

**Comment by GeorgePavlidis** [comment] 2022-09-13 09:52
I have almost identical problem, I'm trying to run a docker container with speechbrain and code that imports speechbrain.  While when the container runs on my local pc everything works fine, but on a server it crashes with exit code 139 due to Segmentation fault (core dumped) whenever it is trying to import speechbrain

**Comment by Adel-Moumen** [comment] 2022-09-13 19:57
> I have almost identical problem, I'm trying to run a docker container with speechbrain and code that imports speechbrain. While when the container runs on my local pc everything works fine, but on a server it crashes with exit code 139 due to Segmentation fault (core dumped) whenever it is trying to import speechbrain

Hello, 

Could you please open a new issue on that with more details? :) 

Thanks!

**Comment by Adel-Moumen** [comment] 2022-09-13 19:57
> Hi, I haven't worked on this for awhile. But today when I tried again, it worked! So I guess this problem has something to do with the server, not with SB.

OK! Thanks. I'm closing this issue. Feel free to re-open it if needed :)

**Closed by Adel-Moumen** 2022-09-13 19:57 UTC
