### ISSUE TITLE
[Bug] huggingface_hub.cached_download() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by SolomidHero** [speechbrain/speechbrain#1459] opened 2022-06-21 16:53 UTC
Hi!

Followed [this model](https://huggingface.co/speechbrain/asr-crdnn-transformerlm-librispeech)
`speechbrain/asr-crdnn-transformerlm-librispeech`
from huggingface models hub.

## Error
code:
```py3
EncoderDecoderASR.from_hparams(
    source=asr_model_source,
    savedir=to_absolute_path('./models'),
    run_opts={'device': torch.device('cpu')}
)
```

trace (catched in pytest):
```tb
score.py:101: in main
    asr_model = EncoderDecoderASR.from_hparams(
../miniconda3/lib/python3.9/site-packages/speechbrain/pretrained/interfaces.py:335: in from_hparams
    pymodule_local_path = fetch(


>               fetched_file = huggingface_hub.cached_download(url, use_auth_token)
E               TypeError: cached_download() takes 1 positional argument but 2 were given

../miniconda3/lib/python3.9/site-packages/speechbrain/pretrained/fetching.py:116: TypeError
```

# Versions

`pip freeze | grep -E hugging|speech`:
```
huggingface-hub==0.8.1
speechbrain==0.5.11
```

version of `huggingface-hub<0.8` works fine

## Solution

use_auth_token should be a keyword argument

Here is my contribution #1458

**Comment by camilotorron** [comment] 2022-06-22 12:12
I had the same issue this morning. I downgraded hugging-face version to 0.7.0 but still not working like yesterday. When performing "verification.verify_files()" this error appears:

'types.SimpleNamespace' object has no attribute 'mean_var_norm_emb'

**Comment by TParcollet** [comment] 2022-06-22 12:15
@mravanelli shouldn't this be fixed now ?

**Comment by Arnold-git** [comment] 2022-06-22 14:13
`from speechbrain.pretrained import SpeakerRecognition
verification = SpeakerRecognition.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb", savedir="pretrained_models/spkrec-ecapa-voxceleb")
score, prediction = verification.verify_files("speechbrain/spkrec-ecapa-voxceleb/example1.wav", "speechbrain/spkrec-ecapa-voxceleb/example2.flac")

print(prediction, score)`

error

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-4-4e6723d977df>](https://localhost:8080/#) in <module>()
      1 from speechbrain.pretrained import SpeakerRecognition
----> 2 verification = SpeakerRecognition.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb")
      3 score, prediction = verification.verify_files("speechbrain/spkrec-ecapa-voxceleb/example1.wav", "speechbrain/spkrec-ecapa-voxceleb/example2.flac")
      4 
      5 print(prediction, score)

1 frames
[/usr/local/lib/python3.7/dist-packages/speechbrain/pretrained/fetching.py](https://localhost:8080/#) in fetch(filename, source, savedir, overwrite, save_filename, use_auth_token)
    114         url = huggingface_hub.hf_hub_url(source, filename)
    115         try:
--> 116             fetched_file = huggingface_hub.cached_download(url, use_auth_token)
    117         except HTTPError as e:
    118             if e.response.status_code == 404:

TypeError: cached_download() takes 1 positional argument but 2 were given`


Meanwhile, this worked perfectly just yesterday evening at about 11 am WAT

**Comment by serkansulun** [comment] 2022-06-22 14:32
Try downgrading huggingface_hub:
`pip uninstall huggingface_hub && pip install huggingface_hub==0.7`

**Comment by mravanelli** [comment] 2022-06-22 15:08
The issue is solved with the latest development branch only. Unfortunately,
it will affect the main branch until we release a new version of
speechbrain (which should be issued soon). As mentioned by Serkan, you can
install huggingface_hub==0.7 and everything will work as before.

**Comment by taylorchu** [comment] 2022-06-23 21:35
```
/usr/local/lib/python3.9/site-packages/huggingface_hub/utils/_deprecation.py:39: FutureWarning: Pass library_name=False as keyword args. From version 0.8 passing these as positional arguments will result in an error
```

**Comment by Arnold-git** [comment] 2022-06-24 11:03
@taylorchu this is just a future warning, you can ignore it with 
```
warnings.filterwarnings("ignore", category=FutureWarning) 
```

**Closed** 2022-07-13 08:22 UTC
