### ISSUE TITLE
how to save ckpt  on each epoch end or N batches instead of N minutes?

### ISSUE THREAD

**Issue by lazerliu** [speechbrain/speechbrain#1143] opened 2021-11-19 11:15 UTC
As title describled,I want to save ckpt on epoch end or N batches,but I only find "ckpt_interval_minutes",thks!

**Comment by Gastron** [comment] 2021-11-19 11:35
Only time interval intra-epoch checkpoints are implemented in Brain. If you need to base it on number of steps, you gotta implement it yourself. You can override `fit()` - probably just copy the basic implementation and change the one if statement that looks at the time since last ckpt. You can access the number of batches seen with `self.step`.

**Comment by Gastron** [comment] 2021-11-19 11:46
I'll add some context for the choice of minutes over number of batches. We felt that basically minutes is the most relevant measurement here, since cluster compute is really reserved in wall clock time.

**Comment by Gastron** [comment] 2021-11-19 11:50
Lastly, if you want to base epochs on numbers of updates rather than seeing the full data, you can pass`looped_nominal_epoch=<num_updates_per_epoch>` in the training data loader options. See [this documentation](https://speechbrain.readthedocs.io/en/latest/API/speechbrain.dataio.dataloader.html#speechbrain.dataio.dataloader.make_dataloader) as well.

**Comment by vadimkantorov** [comment] 2021-11-26 21:05
> I'll add some context for the choice of minutes over number of batches. We felt that basically minutes is the most relevant measurement here, since cluster compute is really reserved in wall clock time.

Unfortunately not the most stable / reproducible one. E.g. if later on you want to resume from a checkpoint from a given iteration / epoch without checking what that should be. Working with checkpoint filenames on disk is also a bit simpler when they are stable. From the reproducibility standpoint, it might make sense to also support traditional checkpointing based on number of iterations or epochs.

**Comment by Gastron** [comment] 2021-11-27 11:48
> Unfortunately not the most stable / reproducible one. E.g. if later on you want to resume from a checkpoint from a given iteration / epoch without checking what that should be. Working with checkpoint filenames on disk is also a bit simpler when they are stable and follow some simple pattern. From the reproducibility standpoint, it might make sense to also support traditional checkpointing based on number of iterations or epochs.

Thanks, the ease of working with predictably named checkpoints is worth considering. Even now, I think basically any workflow is possible, it's more a question of what methods are made most obvious and immediate. The epoch based checkpointing is actually the one that all the SpeechBrain examples and recipes offer as the default. The checkpointer allows the user to provide the name of the checkpoint, I would recommend using that for reproducible checkpoint names. If we want to base an experiment around number of updates, I think the `LoopedLoader` (looped_nominal_epoch argument) is a good tool, but I have only used it without caring about seeing every sample an equal number of times - would be nice to hear about experiences with both considerations simultaneously.

In some recipes I use a Checkpointer instance just to find a suitable checkpoint - that workflow could be made easier and documented a bit better. I think also making it easier to provide a direct path to a checkpoint and getting a `Checkpoint` namedtuple would be a simple but helpful addition.

**Comment by anautsch** [comment] 2023-03-27 08:13
Closing here. Please feel free to re-open.

**Closed by anautsch** 2023-03-27 08:13 UTC
