### ISSUE TITLE
remove system link for windows

### ISSUE THREAD

**Issue by ILG2021** [speechbrain/speechbrain#2298] opened 2023-12-11 10:23 UTC
### Describe the bug

On windows, create any system link will need admin permission and will make the program crash, even worse when deploy as desktop app. So suggest to remove them on windows. it is useless.

### Expected behaviour

no crash for from_hparams and load_audio functions.

**Comment by asumagic** [comment] 2023-12-11 12:28
Duplicate of #2197, we are already aware of this issue and want to fix it.

**Closed by asumagic** 2023-12-11 12:28 UTC
Labels: bug
