### ISSUE TITLE
[Bug]: Space token ' ' found in vocabulary even though it looks like BPE.

### ISSUE THREAD

**Issue by qanastek** [speechbrain/speechbrain#1619] opened 2022-10-24 09:09 UTC
### Describe the bug

Dear Maintainers,

I am currently trying to improve the ASR predictions of the `Wav2Vec2 + CTC + RNN` recipe for CommonVoice by adding an ARPA model during the inference with `pyctcdecode` based on [this issue](https://github.com/speechbrain/speechbrain/issues/1467#issuecomment-1184340981).

So, I trained my Wav2Vec2 + CTC + RNN by using the characters and BPE based tokenization of SentencePiece and adapt it to works with the `EncoderASR.from_hparams` method from SpeechBrain. Everything goes well until now.

Then, I build my ARPA model by using [SriLM from Kaldi](https://github.com/kaldi-asr/kaldi/blob/master/tools/extras/install_srilm.sh) on the data used for building the tokenizer as inputs.

**A sample of the data used for the ARPA model :**

```plain
desogestrel 75 microgrammes à prendre 1 comprimé chaque jour vers midi toujours à la même heure pour 3 mois
lantus solostar 10 unités le soir au coucher pendant 3 mois
tranxene 5 milligrammes 1 gélule le midi 1 gélule au coucher pendant 6 mois
tolexine 50 milligrammes 2 comprimés le soir pendant 15 jours puis 1 le soir ensuite traitement pour 4 semaines à renouveler 1 fois
vitamine c effervescent 1 comprimé dans 1 verre d'eau 1 fois par jour quantité suffisante pour 3 mois
bandelette et lancette adaptées au lecteur de glycémie
1 comprimé le matin et 1 comprimé le soir pendant 8 semaines
```

**A sample of the vocabulary obtains on this file by splitting it into whitespace and removing duplicated terms :**

```plain
125
caféine
crème
revei/
prononcer
k/
applications
ronipyrole
prescrit
trimetazidine
pourcent
macrogol
sodique
spectral
72
kilo
zolpidem
m
ip
500
système
```

**Command line used to build the ARPA with 3-grams :**

```bash
order=3
file=train.txt
/users/ylabrak/kaldi/tools/srilm/bin/i686-m64/ngram-count -unk -vocab vocab.txt -interpolate -kndiscount -gt1min 1 -gt2min 1  -gt3min 1  -gt4min 1 -gt5min 1 -text ${file}.txt -order ${order} -lm ${file}.arpa
```

Then, I make my script for the inference :

```python
import torchaudio
import torch
from pyctcdecode import build_ctcdecoder
from speechbrain.pretrained import EncoderASR

asr_model = EncoderASR.from_hparams(
    source="Run_8896_Chars_No_Underscore",
    savedir="pretrained_models/Run_8896_Chars_No_Underscore",
)

audio, sr  = torchaudio.load('recording_1.wav')
rel_length = torch.tensor([1.0])

encoder_out  = asr_model.encode_batch(audio,rel_length)

labels  = [asr_model.tokenizer.id_to_piece(id).lower() for id in range(asr_model.tokenizer.get_piece_size())]

labels[1]=' '
labels[0] = '<pad>'

# !!! CRASH HERE !!!
decoder = build_ctcdecoder(
    labels,
    "/users/ylabrak/MedicalASR/Inference_ASR/Run_8896_Chars_No_Underscore/ARPA/train.arpa",
    alpha=0.6,
)

res = decoder.decode(encoder_out[0].cpu().numpy())
print(res)
```

**And obtains the following error :**

```plain
(speechbrain_39) ylabrak@helios:~/XXXXX/Inference_ASR$ python predict_one_with_LM.py
Loading the LM will be faster if you build a binary file.
Reading /users/ylabrak/XXXXX/Inference_ASR/model.arpa
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
Traceback (most recent call last):
  File "/users/ylabrak/XXXXX/Inference_ASR/predict_one_with_LM.py", line 34, in <module>
    decoder = build_ctcdecoder(labels, "model.arpa", alpha=0.6)
  File "/users/ylabrak/.conda/envs/speechbrain_39/lib/python3.9/site-packages/pyctcdecode/decoder.py", line 873, in build_ctcdecoder
    alphabet = Alphabet.build_alphabet(labels)
  File "/users/ylabrak/.conda/envs/speechbrain_39/lib/python3.9/site-packages/pyctcdecode/alphabet.py", line 143, in build_alphabet
    _verify_alphabet(labels, is_bpe)
  File "/users/ylabrak/.conda/envs/speechbrain_39/lib/python3.9/site-packages/pyctcdecode/alphabet.py", line 120, in _verify_alphabet
    raise ValueError("Space token ' ' found in vocabulary even though it looks like BPE.")
ValueError: Space token ' ' found in vocabulary even though it looks like BPE.
```

**The ASR characters vocabulary using SentencePiece :**

[100_char.vocab.txt](https://github.com/speechbrain/speechbrain/files/9850284/100_char.vocab.txt)

**The ARPA model itself :**

[train.arpa.txt](https://github.com/speechbrain/speechbrain/files/9850296/train.arpa.txt)

### Expected behaviour

Loading the ARPA model without any crash and make prediction with the LM after the Wav2Vec2 FR + CTC + RNN.

### To Reproduce

```python
import torchaudio
import torch
from pyctcdecode import build_ctcdecoder
from speechbrain.pretrained import EncoderASR

asr_model = EncoderASR.from_hparams(
    source="Run_8896_Chars_No_Underscore",
    savedir="pretrained_models/Run_8896_Chars_No_Underscore",
)

audio, sr  = torchaudio.load('recording_1.wav')
rel_length = torch.tensor([1.0])

encoder_out  = asr_model.encode_batch(audio,rel_length)

labels  = [asr_model.tokenizer.id_to_piece(id).lower() for id in range(asr_model.tokenizer.get_piece_size())]

labels[1]=' '
labels[0] = '<pad>'

# !!! CRASH HERE !!!
decoder = build_ctcdecoder(
    labels,
    "/users/ylabrak/MedicalASR/Inference_ASR/Run_8896_Chars_No_Underscore/ARPA/train.arpa",
    alpha=0.6,
)

res = decoder.decode(encoder_out[0].cpu().numpy())
print(res)
```

### Versions

```plain
Name: speechbrain
Version: 0.5.13
Summary: All-in-one speech toolkit in pure Python and Pytorch
Home-page: https://speechbrain.github.io/
Author: Mirco Ravanelli & Others
Author-email: speechbrain@gmail.com
License:
Location: /users/ylabrak/.conda/envs/speechbrain_39/lib/python3.9/site-packages
Requires: huggingface-hub, hyperpyyaml, joblib, numpy, packaging, scipy, sentencepiece, torch, torchaudio, tqdm
Required-by:
```

```plain
Name: torch
Version: 1.11.0+cu113
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /users/ylabrak/.conda/envs/speechbrain_39/lib/python3.9/site-packages
Requires: typing-extensions
Required-by: flair, hugsvision, pytorch-lightning, speechbrain, timm, torchaudio, torchmetrics, torchtext, torchvision
```

```plain
Name: torchaudio
Version: 0.11.0
Summary: An audio package for PyTorch
Home-page: https://github.com/pytorch/audio
Author: Soumith Chintala, David Pollack, Sean Naren, Peter Goldsborough
Author-email: soumith@pytorch.org
License: UNKNOWN
Location: /users/ylabrak/.conda/envs/speechbrain_39/lib/python3.9/site-packages
Requires: torch
Required-by: speechbrain
```

```plain
Name: pyctcdecode
Version: 0.4.0
Summary: CTC beam search decoder for speech recognition.
Home-page: https://github.com/kensho-technologies/pyctcdecode
Author: Kensho Technologies, LLC.
Author-email: pyctcdecode-maintainer@kensho.com
License: Apache 2.0
Location: /users/ylabrak/.conda/envs/speechbrain_39/lib/python3.9/site-packages
Requires: hypothesis, numpy, pygtrie
Required-by:
```

### Relevant log output

```shell
(speechbrain_39) ylabrak@helios:~/XXXXX/Inference_ASR$ python predict_one_with_LM.py
Loading the LM will be faster if you build a binary file.
Reading /users/ylabrak/XXXXX/Inference_ASR/model.arpa
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
Traceback (most recent call last):
  File "/users/ylabrak/XXXXX/Inference_ASR/predict_one_with_LM.py", line 34, in <module>
    decoder = build_ctcdecoder(labels, "model.arpa", alpha=0.6)
  File "/users/ylabrak/.conda/envs/speechbrain_39/lib/python3.9/site-packages/pyctcdecode/decoder.py", line 873, in build_ctcdecoder
    alphabet = Alphabet.build_alphabet(labels)
  File "/users/ylabrak/.conda/envs/speechbrain_39/lib/python3.9/site-packages/pyctcdecode/alphabet.py", line 143, in build_alphabet
    _verify_alphabet(labels, is_bpe)
  File "/users/ylabrak/.conda/envs/speechbrain_39/lib/python3.9/site-packages/pyctcdecode/alphabet.py", line 120, in _verify_alphabet
    raise ValueError("Space token ' ' found in vocabulary even though it looks like BPE.")
ValueError: Space token ' ' found in vocabulary even though it looks like BPE.
```

### Additional context

It's trained on French.

The inference is made on CPU.

If you need the model for prediction, don't hesitate, I can send you everything by email.

**Comment by TParcollet** [comment] 2022-10-24 09:11
@Antoine-Caubriere @Moumeneb1 please help :D

**Comment by qanastek** [comment] 2022-10-31 17:53
Do you have an update on this ?

**Comment by TParcollet** [comment] 2022-10-31 18:15
Those people are in vacation right now :p

**Comment by Moumeneb1** [comment] 2022-11-01 13:50
Can you please share your labels list I can have a look into that ?
As a first diagnosis, I think your list is considered as BPE and pyctcdecode has a special treatment for [BPEs](https://github.com/kensho-technologies/pyctcdecode/blob/a477d796e232b476ee8b877efba98aa2d822232e/pyctcdecode/alphabet.py#L113) like lists.

Actually if it's BPe you don't need to add the **pad** token and **'    '**, you just need ro replace the <unk> token by **''** 

```python
#remove these lines 
labels[1]=' '
labels[0] = '<pad>'


#Try this line 
labels[0]=""
```

**Comment by qanastek** [comment] 2022-11-02 10:42
I tried to replace the labels like in your following example, and it seems to work. At least removing the `Space token ' ' found in vocabulary even though it looks like BPE` error.

Now, I got this error when I try to apply a ARPA model on my SentencePiece Characters based models :

```plain
Loading the LM will be faster if you build a binary file.
Reading /users/ylabrak/MedicalASR/Inference_ASR/Run_8896_Chars_No_Underscore/ARPA/train.arpa
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
UNK token ▁⁇▁ not found, is this a mistake?
Traceback (most recent call last):
  File "/users/ylabrak/MedicalASR/Inference_ASR/predict_one_with_LM.py", line 55, in <module>
    res = decoder.decode(encoder_out[0].cpu().numpy())
  File "/users/ylabrak/.conda/envs/speechbrain_39/lib/python3.9/site-packages/pyctcdecode/decoder.py", line 679, in decode
    decoded_beams = self.decode_beams(
  File "/users/ylabrak/.conda/envs/speechbrain_39/lib/python3.9/site-packages/pyctcdecode/decoder.py", line 549, in decode_beams
    self._check_logits_dimension(logits)
  File "/users/ylabrak/.conda/envs/speechbrain_39/lib/python3.9/site-packages/pyctcdecode/decoder.py", line 271, in _check_logits_dimension
    raise ValueError(
ValueError: Input logits shape is (1489, 52), but vocabulary is size 53. Need logits of shape: (time, vocabulary)
```

```plain
Loading the LM will be faster if you build a binary file.
Reading /users/ylabrak/MedicalASR/Inference_ASR/Run_4330_SpeechBrain_Ready_Characters/ARPA/train.arpa
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
UNK token ▁⁇▁ not found, is this a mistake?
Traceback (most recent call last):
  File "/users/ylabrak/MedicalASR/Inference_ASR/predict_one_with_LM.py", line 56, in <module>
    res = decoder.decode(encoder_out[0].cpu().numpy())
  File "/users/ylabrak/.conda/envs/speechbrain_39/lib/python3.9/site-packages/pyctcdecode/decoder.py", line 679, in decode
    decoded_beams = self.decode_beams(
  File "/users/ylabrak/.conda/envs/speechbrain_39/lib/python3.9/site-packages/pyctcdecode/decoder.py", line 549, in decode_beams
    self._check_logits_dimension(logits)
  File "/users/ylabrak/.conda/envs/speechbrain_39/lib/python3.9/site-packages/pyctcdecode/decoder.py", line 271, in _check_logits_dimension
    raise ValueError(
ValueError: Input logits shape is (1489, 100), but vocabulary is size 54. Need logits of shape: (time, vocabulary)
```

It looks like to works perfectly for my SentencePiece BPE based models :

```plain
Loading the LM will be faster if you build a binary file.
Reading /users/ylabrak/MedicalASR/Inference_ASR/Run_4332_SpeechBrain_Ready/model.arpa
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
UNK token ▁⁇▁ not found, is this a mistake?
matin et soir
```

Vocabulary of the tokenizer : [100_char.vocab.txt](https://github.com/speechbrain/speechbrain/files/9919360/100_char.vocab.txt)

ARPA model : [train.arpa.txt](https://github.com/speechbrain/speechbrain/files/9919356/train.arpa.txt)

Sample of the training data for the tokenizer / ARPA model : [train_sample.txt](https://github.com/speechbrain/speechbrain/files/9919383/train_sample.txt)

Vocabulary of the ARPA model : [vocab.txt](https://github.com/speechbrain/speechbrain/files/9919359/vocab.txt)

**Comment by Moumeneb1** [comment] 2022-11-02 21:05
Hi ! 

The issue is with pyctcdecode, actually they check if any of the labels starts with **"▁"** [they assume it's a BPE ](https://github.com/kensho-technologies/pyctcdecode/blob/a477d796e232b476ee8b877efba98aa2d822232e/pyctcdecode/alphabet.py#L25) which is not the case for your character level tokenizer. the third label in your list is the **"▁"** and it's the one that makes pyctcdecode think it's a bpe. 

 I don't know what **"▁"** stands for really in your tokenizer, maybe it's the space so can just replace it with space **" "** otherwise a quick fix (not super clean) is to replace with a token "?" or anything  just to run your experiment and then remove it properly from your training vocab.

**Comment by Adel-Moumen** [comment] 2023-01-16 16:44
Hello, 

I assume this issue is solved, and therefore I will close it. 

Feel free to reopen it if needed.   :-)

**Closed by Adel-Moumen** 2023-01-16 16:44 UTC
Labels: bug
