### ISSUE TITLE
[Bug]: 'ENCODERWAV2VECCLASSIFIER' is not a valid ModelType

### ISSUE THREAD

**Issue by Manishthakur2503** [speechbrain/speechbrain#1746] opened 2022-12-06 04:38 UTC
### Describe the bug

**'ENCODERWAV2VECCLASSIFIER' is not a valid ModelType**

### Expected behaviour

When trying to compute the results from https://huggingface.co/speechbrain/emotion-recognition-wav2vec2-IEMOCAP  webpage I am getting this error
![image](https://user-images.githubusercontent.com/102070192/205815858-2668f318-f882-471b-9c71-a069d564e9cd.png)

**Comment by anautsch** [comment] 2022-12-06 07:47
It's reproducible.

The provided code snippet works locally.
```
from speechbrain.pretrained.interfaces import foreign_class
classifier = foreign_class(source="speechbrain/emotion-recognition-wav2vec2-IEMOCAP", pymodule_file="custom_interface.py", classname="CustomEncoderWav2vec2Classifier")
out_prob, score, index, text_lab = classifier.classify_file("speechbrain/emotion-recognition-wav2vec2-IEMOCAP/anger.wav")
print(text_lab)
```

The issue is with the inference API &/or its connection to this model card.

(This is just to confirm that the reported issue is a valid reporting. fyi: our testing covers the code snippets only.)

**Comment by TParcollet** [comment] 2022-12-06 11:38
@anautsch please ping HuggingFace to know what is happening.

**Comment by Adel-Moumen** [comment] 2023-01-16 16:38
Hello guys, 

Any news on this issue, please? Thanks :-)

**Comment by anautsch** [comment] 2023-01-16 16:51
Thx for pinging, forgot to post the status update ... 

There need to be updates to:
* https://github.com/huggingface/api-inference-community/blob/main/docker_images/speechbrain/app/common.py
* https://github.com/huggingface/api-inference-community/blob/main/docker_images/speechbrain/app/pipelines/audio_classification.py

There, thhe `class ModelType(Enum)` needs to be changed for every new custom interface; perhaps also giving little room to having multiple custom interfaces of same class name. 

Their docker can only run what's within SpeechBrain officially. Now, we might be able to give space for known exceptions like this one - but they'll get into conflicts with one another.

@Adel-Moumen any thoughts on ensuring all HF pretrained model class names with custom interfaces have a unique custom interface name? (It implies an update to those who use it; in turn this WebAPI feature.)
... alternatively, should we look into disabling this feature for custom interfaces?

**Comment by Manishthakur2503** [comment] 2023-01-17 08:29
It means I cannot use this model right now? Or is there any method to use it?

**Comment by anautsch** [comment] 2023-01-17 09:02
Hi @Manishthakur2503 you can use the model & it works, please try the code snippets on your device (computer/server). 

Please try the steps steps in the model card README (Install SpeechBrain & Perform Emotion recognition).
https://huggingface.co/speechbrain/emotion-recognition-wav2vec2-IEMOCAP

The HuggingFace WebAPI does not however work for this one. I didn't think about the WebAPI as a first stage testing item (sorry for letting you wait unnecessarily). We don't have a solution for the WebAPI & custom interfaces at the moment. I'd like to leave this issue open until we have one.

**Comment by Manishthakur2503** [comment] 2023-01-17 09:17
The instructions there are not helpful. Why we need to clone the speechbrain repo because something is mentioned there i.e. 'If you want to train model from scratch ' then intsall the repo.

But I want to use pretrained model . So can you please tell me the procedure that how to run it locally?

Thanks

**Comment by AsuMagic** [comment] 2023-01-17 09:29
>  But I want to use pretrained model . So can you please tell me the procedure that how to run it locally?

Then follow the "Install SpeechBrain" (which implies installing SB through `pip` rather than cloning the repo) and the "Perform Emotion recognition" steps. Unless you are hitting an issue of some sort then it's all there is to it.

Cloning the repo is really only useful if you want to train the model, which is not the case.

**Comment by Manishthakur2503** [comment] 2023-01-17 09:34
@AsuMagic  Thanks for the information . But when trying that I got this error
![image](https://user-images.githubusercontent.com/102070192/212861692-cdf6fa70-356c-4902-9d9c-e49271189ad9.png)
![image](https://user-images.githubusercontent.com/102070192/212861779-85b687fe-0b26-425e-bf2f-aeec8d94dc6d.png)

If you have any idea why this is coming please let me know.

Thanks

**Comment by AsuMagic** [comment] 2023-01-17 09:45
I suspect the permission error is due to symbolic links requiring admin privileges on Windows. SB currently uses them in `fetch`, which is implicitly used by the inference interfaces.

I'm not too familiar with SB usage on Windows so I'm not sure what the best approach is. Running the shell as administrator might do the trick, and so should giving your own user (or a new user) [symlink creation privileges](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links), but it seems to be somewhat recommended against to do it with your own user account.

**Comment by anautsch** [comment] 2023-01-17 12:50
Note for later, the interface can also be configured here:
https://huggingface.co/speechbrain/emotion-recognition-wav2vec2-IEMOCAP/blob/main/config.json

which has
```json
{
  "speechbrain_interface": "EncoderWav2vecClassifier"
}
```

while it's [custom interface](https://huggingface.co/speechbrain/emotion-recognition-wav2vec2-IEMOCAP/blob/main/custom_interface.py) is:
```python
class CustomEncoderWav2vec2Classifier(Pretrained):
```

it's indicative of the discrepancy.

@TParcollet should the WebAPI in these cases be deactivated somehow? 
(eg can the config.json file on HF repos be simply empty?)

**Comment by Manishthakur2503** [comment] 2023-01-31 06:21
Any update related to this issue?

**Comment by anautsch** [comment] 2023-01-31 08:24
Hi @Manishthakur2503 not as of now. Did you start using SpeechBrain on your end?
(please do not wait for this to be solved—it is good you keep nudging us, though)

The issue you reported is on a Web API which has a very restrictive configuration (for good reasons). Yet, this clashes with SpeechBrain's philosophy of providing developers maximum freedom in how they like to code. This includes choosing class names for custom pretrained models. Thank you for highlighting the topic, at least now it is known (SpeechBrain is community-driven only).

Can't make promises here; my estimate would be that when pretrained interfaces might get refactored at some point, someone might pick this up again (if aware) and fix it. A PR from the SpeechBrain community would be helpful here.

---

Were you able to fix the issue you discussed with @AsuMagic ?
(afaik SpeechBrain's core team has no Windows device in use)

**Comment by TParcollet** [comment] 2023-01-31 08:27
This requires a change in HuggingFace api, an issue should certainly be opened in their side.

**Comment by Manishthakur2503** [comment] 2023-01-31 12:16
Ok thanks for the information

**Comment by Adel-Moumen** [comment] 2023-09-02 12:17
Hello, 

We turned off the web API for this model. We will turn on when it will be solved on the HF side. Therefore, I am closing this issue as this is not related to us... If you want to keep us updated, you should open a discussion on the HF model card. 

Best,
Adel

**Closed by Adel-Moumen** 2023-09-02 12:17 UTC
Labels: bug
