### ISSUE TITLE
Kmeans .fit() should be changed to .partial_fit()

### ISSUE THREAD

**Issue by Beilong-Tang** [speechbrain/speechbrain#2602] opened 2024-07-11 07:13 UTC
### Describe the bug

Here
https://github.com/speechbrain/speechbrain/blob/431760bd241a501af9c86f3e52d3bf3194a2f185/speechbrain/utils/kmeans.py#L171

You use .fit method on partial of the data. However, I think this should be partial_fit() to update on a small chunk of data. If you call .fit. The kmeans will only apply to that specific data while removing all the previous results. 
But I am also not so sure. If this is the case, all experiments built on kmeans would be wrong. 

### Expected behaviour

Please consider changing the line of code.

**Comment by poonehmousavi** [comment] 2024-08-15 14:10
Thanks, @Beilong-Tang for raising this point. The issue is addressed in [this PR](https://github.com/speechbrain/speechbrain/pull/2642).

**Closed** 2024-10-15 13:59 UTC
Labels: bug
