### ISSUE TITLE
Language Model in Speech Recognition template not working

### ISSUE THREAD

**Issue by maaly-zayed** [speechbrain/speechbrain#1531] opened 2022-08-04 09:41 UTC
I tried to run the Language Model in the  [speech recognition](https://github.com/speechbrain/speechbrain/tree/develop/templates/speech_recognition) template but unfortunately this error appeared.
ImportError: There is no such class as templates.speech_recognition.LM.custom_model.CustomModel

Note: I installed speechbrain inside an activate environment, also I upgraded speechbrain.

![speechbrain_issue](https://user-images.githubusercontent.com/70846058/182815196-f94fe0f6-529b-4d14-8965-8e782304a019.png)

Any idea what is causing this issue?

**Comment by TParcollet** [comment] 2022-08-10 09:21
Hi, I tried with a fresh install, and everything works fine. Hence I am not able to reproduce the error. It is most likely that this is due to a problem in the installation or in the path. I see that you are using Windows, I have no real experience in setting properly the path there ...

**Comment by Hemanshu-Bhargav** [comment] 2022-08-12 21:55
Hi, 

I have the same issue using a Linux system (Google Colab). I've ensured that the custom model is in the correct directory (as suggested in [https://speechbrain.discourse.group/t/importerror-there-is-no-such-class-as-custom-model-custommodel/130](this post)) but it hasn't solved the problem.

Does anyone have any other suggestions?

Thanks,
Hemanshu

**Comment by suhasiniselvam** [comment] 2022-08-16 04:10
In RNNLM.yaml file , check line 66
**Change** - model:!new:templates.speech_recognition.Lm.Custom_model.CustomModel .... as
                model:!new:Custom_model.CustomModel
           

I hope it can clear your error

**Comment by Hemanshu-Bhargav** [comment] 2022-08-16 05:27
@suhasiniselvam Thanks for your reply. I'm not sure if it will work for @maaly-zayed but I receive the same error regardless. Although, I'm not sure if it should matter, since providing a more complete path shouldn't be an issue?

**Comment by anautsch** [comment] 2022-09-13 07:57
Hi @maaly-zayed is the error still occuring?
Yesterday, the templates worked for me without problems. Are you starting them from within the `templates/speech_recognition/LM` folder? In that folder is a 
https://github.com/speechbrain/speechbrain/blob/53455cab284f6665c3703b1d5e6c8e9509969dcd/templates/speech_recognition/LM/custom_model.py#L20

which is (usually) only available to the python path if python is started from that directory.

**Comment by anautsch** [comment] 2022-09-13 16:16
Could reproduce the error when copying the `LM` folder somewhere else on my system and re-running it.

The yaml file overspecifies the path for the custom model:
https://github.com/speechbrain/speechbrain/blob/85c6a0dd807d8ab16be6a7a424cc791662d107e7/templates/speech_recognition/LM/RNNLM.yaml#L67

Here's the diff patch to get it working:
```
--- RNNLM.yaml
+++ RNNLM.yaml
@@ -64,7 +64,7 @@
 # To design a custom model, either just edit the simple CustomModel
 # class that's listed here, or replace this `!new` call with a line
 # pointing to a different file you've defined..
-model: !new:templates.speech_recognition.LM.custom_model.CustomModel
+model: !new:custom_model.CustomModel
     embedding_dim: !ref <emb_dim>
     rnn_size: !ref <rnn_size>
     layers: !ref <layers>
```

**Comment by Adel-Moumen** [comment] 2022-11-03 16:48
Hello @maaly-zayed,

Is there some news on this issue, please? Thanks! :)

**Comment by anautsch** [comment] 2023-03-27 09:43
Please check out the latest minor version (it should be fixed). Closing here. Please feel free to re-open.

**Closed by anautsch** 2023-03-27 09:43 UTC
